config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :beers, only: :show
  resources :favourites, only: [:index, :create, :destroy]
  resources :recommendations, only: [:index]
  resources :scans, only: [:new, :create]

  get 'pages/test'
  get 'pages/no_match', to: 'pages#no_match', as: 'no_match'
  get '/test_matching/:beers_to_test', to: "pages#test_matching"
  get 'pages/autocomplete', to: 'pages#autocomplete', as: 'autocomplete'
end

app/controllers/scans_controller.rb
# require "google/cloud/vision"
class ScansController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]

  def new
    @page_title = "scan"
  end

  def create
    res = Cloudinary::Uploader.upload(params[:image])
    uploaded_url = res["url"]
    google_vision = GoogleVisionService.new(uploaded_url)
    @scan_results = google_vision.texts_from_image
    beer = Beer.find_best_matching_beer_with_score(@scan_results)
    if beer[1] < 5
      redirect_to no_match_path
    else
      redirect_to beer_path(beer[0])
    end
  end
end

app/views/scans/new.html.erb
<div id="loading" class="d-none"><div id="loading-gif"></div></div>
<img src="/" alt="" class="d-none" id="snap_video">
<canvas id="canvas" class="d-none"></canvas>
<%= form_with(url: scans_path, method: "POST", local: true, multipart: true, id: 'form-scan') do %>
  <%= hidden_field_tag(:image) %>
<% end %>

<div class="overlay-video">
  <div class="overlay-border">
    <h3>Scan l'étiquette de ta bière</h3>
  </div>
</div>

<video id="video" autoplay muted playsinline></video>

<div class="navbar-scan">
  <%= link_to url_for(:back) do %>
  <div><i class="fas fa-times"></i></div>
  <% end %>
  <i class="fas fa-camera" id="startbutton"></i>
</div>