config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :beers, only: :show
  resources :favourites, only: [:index, :create, :destroy]
  resources :recommendations, only: [:index]
  resources :scans, only: [:new, :create]

  get 'pages/test'
  get 'pages/no_match', to: 'pages#no_match', as: 'no_match'
  get '/test_matching/:beers_to_test', to: "pages#test_matching"
  get 'pages/autocomplete', to: 'pages#autocomplete', as: 'autocomplete'
end

app/views/pages/home.html.erb
<!-- <#%= image_tag"logo.svg", alt: "alttext", class: "logo" %> -->
<div>
  <div class="wrapper-button">
    <div class="d-flex justify-content-between top-buttons">
      <%= link_to favourites_path, class: 'text-center sign_in_required' do%>
        <i class="fas fa-heart white"></i>
        <p>Ma cave</p>
      <% end %>
      <%= link_to recommendations_path, class: 'text-center sign_in_required' do%>
        <i class="fas fa-compass"></i>
        <p>Découvrir</p>
      <% end %>
    </div>
    <div class="d-flex flex-column align-items-center flex-grow-1 justify-content-around">
      <%= image_tag "Logo-tete-blanche.png", alt: "biernard", class: "logo-home", width: "100px" %>
      <%#= link_to "sign out", destroy_user_session_path, method: :delete %>
      <div class="d-flex justify-content-center">
        <%= link_to new_scan_path do %>
        <div class="awesome-button">
          <i class="fas fa-camera"></i>
        </div>
        <% end %>
      </div>
      <div class="text-info">
        <h3>Scanne tes bières</h3>
      </div>
    </div>
  </div>
</div>

app/views/pages/no_match.html.erb
<div class="biernard-bubble">
  <%= link_to root_path do %>
    <%= image_tag "https://media.biernard.com/iw/br/_next/static/images/biernard-bierologue-digital-350-b0900e88fe20250cdceebcaf9b0a202e.png", alt: "Biernard - Biérologue Digital" %>
  <% end %>
  <div class="speech-bubble">
    <p><strong>Fichtre !</strong> Je ne trouve pas ta bière, tu peux saisir son nom :</p>
  </div>
</div>
<hr align="center" width="50%">
<!-- <h1 class="reco-title">Fichtre !</h1>
<p class="reco-description">Je ne trouve pas ta bière, tu peux saisir son nom :</p> -->
<div class="wrong_beer_search">
  <%= form_tag beer_path("no_match"), method: :get do %>
  <%= text_field_tag :query,
      params[:query],
      class: "form-control autocomplete",
      placeholder: "Cherche ta bière..."
    %>
    <ul class="search-result">

    </ul>
    <%= submit_tag "Chercher", class: "search-btn" %>
  <% end %>
</div>

app/views/pages/test_matching.html.erb
<h1>test results</h1>

<%= good = @matching_data.count {|result| result[:good_matching]} %>
<%= all = @matching_data.count %>
<%= google_errors = @matching_data.count {|result| result[:texts].size.zero? }  %>
<%= "#{good.fdiv(all - google_errors).round(2) * 100}%" %>
<%= "#{@duration.round} s " %>
<%= "#{@duration.fdiv(all).round(2) * 100}ms par beer" %>

<table>
    <thead>
        <tr>
            <th>Result</th>
            <th>Image</th>
            <th>Texts</th>
            <th>Beer Name</th>
            <th>Beer Brewery</th>
            <th>Beer Name Matched</th>
            <th>Beer Brewery Matched</th>
            <th>Score</th>
        </tr>
    </thead>
    <tbody>
      <% @matching_data.each do |result| %>
        <tr>
            <td><%= result[:good_matching] %></td>
            <td><%= image_tag result[:beer_image], alt: "alttext", width: "50px"%></td>
            <td><%= result[:texts] %></td>
            <td><%= result[:beer_name] %></td>
            <td><%= result[:beer_brewery] %></td>
            <td><%= result[:matched_beer_name] %></td>
            <td><%= result[:matched_beer_brewery] %></td>
            <td><%= result[:score].round(2) %></td>
        </tr>
      <% end %>
    </tbody>
</table>

<%= JSON.generate(@matching_data) %>